### ISSUE TITLE
configure file assume the user name is "ubuntu"

### ISSUE THREAD

**Issue by Elmapul** [pol2095/Flash-Player-Projector-64-bit-standalone-install-for-Ubuntu#2]
please fix this line:

Exec=/home/ubuntu/executable/flashplaye

replacing ubuntu with $USER should do the trick.
if that dont work for all distros, seting the result of whoami  to an variable then assing it.

**Comment by pol2095** [comment]
It's strange, the line is :
`echo "Exec=$HOME/bin/flashplayer %f" >> flashplayer.desktop`

**Comment by Elmapul** [comment]
check the tar avaliable for download.
indeed the code on github says $HOME but the code on the tar wasnt updated yet (Direct download)

**Comment by pol2095** [comment]
It's fixed.
